[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
lutrii_recurring = "146BGDDLG4yRYXfNCCDdRRmCAYTrGddCgY14n4ekxJyF"
lutrii_merchant_registry = "3RkcL88V6dyHRCJFyGZ54R1u1KcHqeYB24MA38894Eex"

[programs.devnet]
lutrii_recurring = "146BGDDLG4yRYXfNCCDdRRmCAYTrGddCgY14n4ekxJyF"
lutrii_merchant_registry = "3RkcL88V6dyHRCJFyGZ54R1u1KcHqeYB24MA38894Eex"

[programs.mainnet]
lutrii_recurring = "146BGDDLG4yRYXfNCCDdRRmCAYTrGddCgY14n4ekxJyF"
lutrii_merchant_registry = "3RkcL88V6dyHRCJFyGZ54R1u1KcHqeYB24MA38894Eex"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"

[[test.validator.clone]]
# Jupiter Aggregator V6
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"

[[test.validator.clone]]
# USDC Mint (Token-2022)
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
